<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class ProductionPlanning extends CI_Controller{
    function __construct()
    {
        $models = 'production_planning/Production_planning_model';

        parent::__construct();
        $this->sess_id = $this->session->userdata('userid');
        $this->load->helper(array('url'));
        $this->load->model($models,'Production_planning_model');
    } 

    function index(){
        $data = array();
        $this->load->view('production_planning/index',$data);
    }

    /*
     * Global Function
     */

    // get datas Holidays
    function getDataHolidays(){
      
        $dataHoliday  = $this->Production_planning_model->getDataHolidays();
        $dataHolidays = json_encode($dataHoliday);
        echo $dataHolidays;;
    }   

    // get datas Planning
    function getDataPlannigs(){
      
        $data = $this->Production_planning_model->getDataLinePlannings();
        $datas = json_encode($data);
        echo $datas;
    }   
}
