<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class ProductionPlanning extends CI_Controller{
    function __construct(){
        $models = 'production_planning/Production_planning_model';

        parent::__construct();
        $this->sess_id = $this->session->userdata('userid');
        $this->load->helper(array('url'));
        $this->load->model($models,'Production_planning_model');
    } 

    function index(){
        $data = array();
        $this->load->view('production_planning/ProductionPlanning2',$data);
    }
    
    // get data planning by line

    function planingLine($line){        
        $data['line'] = $line;

        $this->load->view('production_planning/PlaningLine',$data);
    }
        
    /*
     * Global Function
     */

    // get data planing line
    function getDataPlanningByLine(){
        # code...
        $line = $_GET['lineName'];
            
        $resultLine  = $this->Production_planning_model->getDataPlanningByLine($line);
        $resultLineData = json_encode($resultLine);
        echo $resultLineData;
    }
 
    // get datas Holidays
    function getDataHolidays(){
      
        $dataHoliday  = $this->Production_planning_model->getDataHolidays();
        $dataHolidays = json_encode($dataHoliday);
        echo $dataHolidays;;
    }   

    // get datas Planning
    function getDataPlannigs(){
      
        $data = $this->Production_planning_model->getDataLinePlannings();
        $datas = json_encode($data);
        echo $datas;
    }   
}
