<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class ProductionPlanning extends CI_Controller{
    function __construct()
    {
        $models = 'production_planning/Production_planning_model';

        parent::__construct();
        $this->sess_id = $this->session->userdata('userid');
        $this->load->helper(array('url'));
        $this->load->model($models,'Production_planning_model');
    } 

    function index(){
        
        // $data = array();
        $data['moldingstyle']=$this->Production_planning_model->get_all();
        $this->load->view('production_planning/index',$data);
    }


    /*
     * Screen C
     */
    function viewScreenC()
    {   
      //  $data = array();
        $data['js'] = $this->load->view('js','',true);
        $data['content'] = $this->load->view('admin_sewing_screen_3/Screen_C', $data, true);
        $this->parser->parse(TEMPLATE.'/content', $data);
    }

    /*
     * Global Function
     */

    // first slide
    function viewFirstSlide(){
        $data = $this->Admin_sewing_screen_3_model->getDataSlideFirst();
        $datas = json_encode($data);
        echo $datas;
    }   

    // second slide
    function viewSecondSlide(){
        # code...
        $lineName = $_GET['lineName'];
        $tgl      = $_GET['tgl'];

        $data  = $this->Admin_sewing_screen_3_model->getDataSlideSecond($lineName, $tgl);
        $datas = json_encode($data);
        echo $datas;
    }
}
