<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class SewingLiveReportFloorThirdA extends CI_Controller{
    function __construct(){
        $models = 'production_planning/Production_planning_model';

        parent::__construct();
        $this->sess_id = $this->session->userdata('userid');
        $this->load->helper(array('url'));
        $this->load->model($models,'Production_planning_model');
    } 

    function index(){
        $data = array();
        $this->load->view('sewing_live_report_view/SewingLiveReportFloorThirdA',$data);
    } 

}
